name: Bug Report
description: Report a bug you have found.

title: "[BUG] Title"
labels: bug

body:
    - type: checkboxes
      id: existing-issue
      attributes:
          label: Is there an existing issue for this?
          description: Search for an existing issue to avoid duplicates.
          options:
              - label: I have searched for an [existing issue](https://github.com/EasyScriptJS/EasyScript/issues).
                required: true
    - type: input
      id: what
      attributes:
          label: What module?
          description: What module is affected by this error?
      validations:
          required: true
    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected Behavior
          description: What should happen?
      validations:
          required: true
    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual Behavior
          description: What happens instead?
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to Reproduce
          description: How can we reproduce this bug?
      validations:
          required: true
    - type: markdown
      attributes:
          value: |
              ### Environment Details
    - type: input
      id: node-version
      attributes:
          label: Node.js Version
          description: Which version of Node.js are you using?
      validations:
          required: true
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: What is the version of Easy Script you are using?
      validations:
          required: true
