name: PR

on:
    - pull_request_target

concurrency:
    group: ${{ github.ref }}-pr
    cancel-in-progress: false

jobs:
    label:
        name: Label
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: "${{ secrets.BOT }}"
                  sync-labels: true
